services:
  web:
    image: nginxinc/nginx-unprivileged:1.28.2-alpine
    container_name: nginx-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:${NGINX_PORT}'
    networks:
      - backend
      - frontend
    security_opt:
      - no-new-privileges=true
    read_only: true # дочерницые процессы(докер) не получит права выше, чем у родителя(флаг в ядре)
    tmpfs:
      - /tmp:mode=1777 
      - /var/cache/nginx:mode=1777 
      - /var/run:mode=1777 
    healthcheck:
      test: ["CMD", "curl", "-f","http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      - app
  app:
    image: my-web-app:1.0
    container_name: my-web
    networks:
      - backend
    security_opt:
      - no-new-privileges=true
    read_only: true 
    # tmpfs:
      # - /tmp
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080')"]
      interval: 30s
      timeout: 5s
      retries: 3
    environment:
      #- PYTHONDONTWRITEBYTECODE=1
      - PORT=${FLASK_PORT}   
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge